### ISSUE TITLE
fabric api

### ISSUE THREAD

**Issue by gamerchamper** [8bitFra/Vanilla-Spoof#4]
It says it requires any version of the fabric api to be installed when I already have it installed.

**Comment by 8bitFra** [comment]
What version are you using?

**Comment by gamerchamper** [comment]
fabric-loader-0.14.10-1.19
fabric-api-0.58.0+1.19
vanilla-spoof-1.0.3

Note: various other mods also say it requires Fabric API any version even though I already have it. And if I add another Fabric API version, it says I need to remove one of them..

**Comment by 8bitFra** [comment]
The problem is probably related to the fact that the mod is not compatible with that version of Fabric API, the dependency message you read is defined by an independent configuration that I had not integrated, please try to delete the old version of Fabric API and update it to version 0.59.0 or newer.
